feat: switch to wsl-vpnkit v3

diff --git a/docker/root/usr/local/bin/wsl-vpnkit b/docker/root/usr/local/bin/wsl-vpnkit
--- a/docker/root/usr/local/bin/wsl-vpnkit
+++ b/docker/root/usr/local/bin/wsl-vpnkit
@@ -20,101 +20,87 @@
 # USE OR OTHER DEALINGS IN THE SOFTWARE.
 
 set -eo pipefail
+# shellcheck source=../../../etc/DockerInWsl/diw-commons.sh
 . /etc/DockerInWsl/diw-commons.sh
 _diw_plugin_globalvars
 
-CONF_PATH="$LOCALAPPDATA/DockerInWSL/wsl-vpnkit/wsl-vpnkit.conf"
-HTTP_PROXY_CONFIG_PATH="$LOCALAPPDATA/DockerInWSL/wsl-vpnkit/http-proxy.json"
-SOCKET_PATH="/var/run/wsl-vpnkit.sock"
-PIPE_PATH="//./pipe/wsl-vpnkit"
-TAP_PID_PATH="/var/run/vpnkit-tap-vsockd.pid"
+CONF_PATH="/etc/DockerInWsl/wsl-vpnkit.conf"
 
-VPNKIT_PATH="$LOCALAPPDATA/DockerInWSL/vpnkit.exe"
-NPIPERELAY_PATH="$LOCALAPPDATA/DockerInWSL/npiperelay.exe"
+GVPROXY_PATH="$DIW_DRIVERDIR/wsl-gvproxy.exe"
+VM_PID=
 
-echo "starting wsl-vpnkit"
+log "starting wsl-vpnkit"
 
 # Load defaults
 if [ -f "/etc/vpnkit/defaults.conf" ]; then
+  # shellcheck source=../../../etc/vpnkit/defaults.conf
   . /etc/vpnkit/defaults.conf
 fi
 
 #  Load user config if needed
 if [ -f "$CONF_PATH" ]; then
   . "$CONF_PATH"
-  echo "loaded config: $CONF_PATH"
+  log "loaded config: $CONF_PATH"
 fi
 
 # set defaults if variable is not already set
 TAP_NAME=${TAP_NAME:-$DEFAULT_TAP_NAME}
+VPNKIT_SUBNET=${VPNKIT_SUBNET:-$DEFAULT_VPNKIT_SUBNET}
 VPNKIT_GATEWAY_IP=${VPNKIT_GATEWAY_IP:-$DEFAULT_VPNKIT_GATEWAY_IP}
 VPNKIT_HOST_IP=${VPNKIT_HOST_IP:-$DEFAULT_VPNKIT_HOST_IP}
 VPNKIT_LOWEST_IP=${VPNKIT_LOWEST_IP:-$DEFAULT_VPNKIT_LOWEST_IP}
-VPNKIT_HIGHEST_IP=${VPNKIT_HIGHEST_IP:-$DEFAULT_VPNKIT_HIGHEST_IP}
 VPNKIT_DEBUG=${VPNKIT_DEBUG:-$DEFAULT_VPNKIT_DEBUG}
-VPNKIT_PORT_MAX_IDLE=${VPNKIT_PORT_MAX_IDLE:-$DEFAULT_VPNKIT_PORT_MAX_IDLE}
 CHECK_DNS=${CHECK_DNS:-$DEFAULT_CHECK_DNS}
 CHECK_HOST=${CHECK_HOST:-$DEFAULT_CHECK_HOST}
 DNS_IP=${DNS_IP:-$DEFAULT_DNS_IP}
 
-VPNKIT_WSL2_IP="$VPNKIT_LOWEST_IP"
-WSL2_GATEWAY_IP="$(cat /etc/resolv.conf | awk '/^nameserver/ {print $2}')"
+WSL2_GATEWAY_IP="$(ip -o -f inet addr show eth0 | awk '/scope global/ {print $4}' | head -n1 | cut -d'/' -f1 |  awk '{OFS="."; split($0,a,"."); print a[1],a[2],a[3],"1"}')"
+WSL2_TAP_NAME=eth0
+WSL2_VM_IP="$(ifconfig $WSL2_TAP_NAME | awk '/inet /{print substr($2, 6)}')"
 
-relay () {
-    echo "starting socat-npiperelay..."
-    NPIPERELAY_SOCAT_PATH=/run/npiperelay.exe
-    ln -sf "$NPIPERELAY_PATH" "$NPIPERELAY_SOCAT_PATH"
-    echo "using $NPIPERELAY_SOCAT_PATH for npiperelay.exe"
-    socat UNIX-LISTEN:$SOCKET_PATH,fork,umask=007 EXEC:"$NPIPERELAY_SOCAT_PATH -ep -s $PIPE_PATH",nofork
+run () {
+    log "starting gvproxy at $GVPROXY_PATH..."
+    wsl-vm \
+      -path "$GVPROXY_PATH" \
+      -iface "$TAP_NAME" \
+      -subnet "$VPNKIT_SUBNET" \
+      -gateway-ip "$VPNKIT_GATEWAY_IP" \
+      -host-ip "$VPNKIT_HOST_IP" \
+      -vm-ip "$VPNKIT_LOWEST_IP" \
+      -debug="$VPNKIT_DEBUG" &
+    VM_PID=$!
+    log "started gvproxy"
 }
 
-relay_wait () {
-    echo "waiting for $SOCKET_PATH ..."
-    while [ ! -S "$SOCKET_PATH" ]; do
+tap_wait () {
+    log "waiting for dhcp..."
+    c=1
+    d=0
+    set +eo pipefail
+    while [ "$c" -eq 1 ] && [ "$d" -eq 0 ]; do
         sleep 0.1
+        ip a s "$TAP_NAME" | grep -E -o 'inet [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
+        c=$?
+        kill -0 $VM_PID
+        d=$?
     done
-    echo "found $SOCKET_PATH"
-}
-
-vpnkit () {
-    echo "starting vpnkit..."
-    WIN_PIPE_PATH=$(echo $PIPE_PATH | sed -e "s:/:\\\:g")
-    
-    CMD="\"$VPNKIT_PATH\" \
-        --ethernet '$WIN_PIPE_PATH' \
-        --gateway-ip '$VPNKIT_GATEWAY_IP' \
-        --host-ip '$VPNKIT_HOST_IP' \
-        --lowest-ip '$VPNKIT_LOWEST_IP' \
-        --highest-ip '$VPNKIT_HIGHEST_IP' \
-        --port-max-idle-time '$VPNKIT_PORT_MAX_IDLE' \
-    "
-    if [ "$VPNKIT_DEBUG" ]; then
-        CMD="$CMD"' --debug'
+    if [ "$d" -eq 1 ]; then
+        log "wsl-vm exited"
+        exit 1
     fi
-    if [ -f "$HTTP_PROXY_CONFIG_PATH" ]; then
-        WIN_HTTP_PROXY_CONFIG_PATH=$(wslpath -m "$HTTP_PROXY_CONFIG_PATH")
-        echo "using $WIN_HTTP_PROXY_CONFIG_PATH"
-        CMD="$CMD"" --http '$WIN_HTTP_PROXY_CONFIG_PATH'"
-    fi
-    echo "eval: $CMD"
-    eval "$CMD"
-}
-
-tap () {
-    echo "starting vpnkit-tap-vsockd..."
-    vpnkit-tap-vsockd --tap "$TAP_NAME" --path $SOCKET_PATH --daemon --pid $TAP_PID_PATH
-    echo "started vpnkit-tap-vsockd"
+    set -eo pipefail
+    log "dhcp completed"
 }
 
 ipconfig () {
-    echo "configuring ip..."
+    log "configuring ip..."
     ip a add "$VPNKIT_WSL2_IP/255.255.255.0" dev "$TAP_NAME" || true
     ip link set dev "$TAP_NAME" up
     ip route | grep -e "$VPNKIT_GATEWAY_IP" -e 'default' | tr '\n' '\0' | xargs -0 -n 1 sh -c 'ip route del $1' argv0
     ip route replace default via "$VPNKIT_GATEWAY_IP" dev "$TAP_NAME"
-    echo "ip config done"
+    log "ip config done"
 
-    echo "adding rules to iptables..."
+    log "adding rules to iptables..."
     iptables -t nat -A PREROUTING -d "$WSL2_GATEWAY_IP/32" -p udp -m udp --dport 53 -j DNAT --to-destination "$DNS_IP:53"
     iptables -t nat -A PREROUTING -d "$WSL2_GATEWAY_IP/32" -p tcp -m tcp --dport 53 -j DNAT --to-destination "$DNS_IP:53"
     iptables -t nat -A PREROUTING -d "$WSL2_GATEWAY_IP/32" -j DNAT --to-destination "$VPNKIT_HOST_IP"
@@ -131,21 +117,21 @@ ipconfig () {
 
 check_ping () {
     ping "-$1" -c 1 "$3" >/dev/null && \
-        echo "check: ✔️ ping success to IPv$1 $2 ($3)" || \
-        echo "check: $([ $1 = '6' ] && echo '➖' || echo '❌') ping fail to IPv$1 $2 ($3)"
+        log "check: ✔️ ping success to IPv$1 $2 ($3)" || \
+        log "check: $([ $1 = '6' ] && echo '➖' || echo '❌') ping fail to IPv$1 $2 ($3)"
 }
 
 check_dns () {
     TYPE=$([ "$1" = "4" ] && echo 'A' || echo 'AAAA')
     nslookup "-type=$TYPE" "$2" "$3" >/dev/null && \
-        echo "check: ✔️ nslookup success for $2 $TYPE using $3" || \
-        echo "check: ❌ nslookup fail for $2 $TYPE using $3"
+        log "check: ✔️ nslookup success for $2 $TYPE using $3" || \
+        log "check: ❌ nslookup fail for $2 $TYPE using $3"
 }
 
 check_https () {
     wget --spider -q $1 && \
-        echo "check: ✔️ wget success for $1" || \
-        echo "check: ❌ wget fail for $1"
+        log "check: ✔️ wget success for $1" || \
+        log "check: ❌ wget fail for $1"
 }
 
 check () {
@@ -167,45 +153,45 @@ check () {
 
 cleanup () {
     set +eo pipefail
-    echo "cleaning up iptables..."
+    log "cleaning up iptables..."
     iptables -t nat -S | grep "$VPNKIT_GATEWAY_IP" | cut -d " " -f 2- | tr '\n' '\0' | xargs -0 -r -n 1 sh -c 'iptables -t nat -D $1' argv0
     iptables -t nat -S | grep "$VPNKIT_HOST_IP" | cut -d " " -f 2- | tr '\n' '\0' | xargs -0 -r -n 1 sh -c 'iptables -t nat -D $1' argv0
     iptables -t nat -S | grep "$TAP_NAME" | cut -d " " -f 2- | tr '\n' '\0' | xargs -0 -r -n 1 sh -c 'iptables -t nat -D $1' argv0
-    echo "iptables cleanup done"
+    iptables -t nat -S | grep "$DNS_IP" | cut -d " " -f 2- | tr '\n' '\0' | xargs -0 -r -n 1 sh -c 'iptables -t nat -D $1' argv0
+    log "iptables cleanup done"
 
-    echo "cleaning up ip..."
+    log "cleaning up ip..."
     ip route | grep -e "$VPNKIT_GATEWAY_IP" -e 'default' | tr '\n' '\0' | xargs -r -0 -n 1 sh -c 'ip route del $1' argv0
     ip link set dev "$TAP_NAME" down || true
-    ip route add default via "$WSL2_GATEWAY_IP" dev eth0
-    echo "ip cleanup done"
+    ip link delete "$TAP_NAME" || true
+    ip addr add "$WSL2_VM_IP/255.255.255.0" dev "$WSL2_TAP_NAME"
+    ip route add default via "$WSL2_GATEWAY_IP" dev "$WSL2_TAP_NAME"
+    log "ip cleanup done"
 
-    if [ -f "$TAP_PID_PATH" ]; then
-        echo "stopping vpnkit-tap-vsockd"
-        kill -- "-$(cat $TAP_PID_PATH)" || true
-        echo "stopped vpnkit-tap-vsockd"
-    fi
+    log "restoring WSL 2 ip route..."
+      
+    log "restored WSL 2 ip route"
+
     set -eo pipefail
-    $CMDSHELL /V:OFF /C 'taskkill /F /T /IM vpnkit.exe' 2>/dev/null || :
+    $CMDSHELL /V:OFF /C 'taskkill /F /T /IM wsl-gvproxy.exe' 2>/dev/null || :
 }
 
 close () {
     cleanup
-    echo "stopped wsl-vpnkit"
+    log "stopped wsl-vpnkit"
     kill 0
 }
 
 if [ "$(id -u)" -ne "0" ]; then
-    echo "Please run this script as root"
+    log "Please run this script as root"
     exit 1
 fi
 
 cleanup
-relay &
-relay_wait
-vpnkit &
-tap
+run
+tap_wait
 ipconfig
 check
-trap close EXIT
-trap exit INT TERM
+trap close exit
+trap exit int term
 wait
